#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
LLaMA three-stage causal path patching.

Fixed functional positions:
    source   = role_adj_adv
    mediator = inst_all
    receiver = last

For each candidate chain:
    Role@source -> Instruction@mediator -> Last@receiver

Interventions
-------------
clean
corrupted

C1 source_patched
C2 source_patched + mediator_blocked

C3 clean_mediator_patched
C4 clean_mediator_patched + receiver_blocked

C5 source_induced_mediator_patched
C6 source_induced_mediator_patched + receiver_blocked

C7 source_patched + receiver_blocked

C5/C6 are the important full-chain test:
the mediator activation is first generated by actually patching the Role source
in the corrupted prompt, then that source-induced mediator state is transplanted
into a fresh corrupted run, with/without the Last receiver available.
"""

import argparse
import json
import math
import os
import sys
from pathlib import Path

import pandas as pd
import torch
from tqdm import tqdm

# Shared helpers for prompt construction, scoring, and model setup.

THIS_FILE = Path(__file__).resolve()
REPO_ROOT = THIS_FILE.parents[3]
CODE_DIR = THIS_FILE.parent / "code"

if str(CODE_DIR) not in sys.path:
    sys.path.insert(0, str(CODE_DIR))

import model_adapter as base


def span_positions(rng):
    """[(start,end)] -> [start, ..., end-1]."""
    start, end = rng[0]
    return list(range(int(start), int(end)))


def safe_div(num, den):
    if abs(den) < 1e-12:
        return math.nan
    return num / den


@torch.no_grad()
def run_one_example(
    model,
    clean_tokens,
    corrupt_tokens,
    clean_ranges,
    corrupt_ranges,
    source_layer,
    source_head,
    mediator_layer,
    mediator_head,
    receiver_layer,
    receiver_head,
    correct_token_id,
    wrong_token_id,
):
    # ---------------------------------------------------------
    # Positions
    # ---------------------------------------------------------
    clean_seqlen = clean_tokens.shape[-1]
    corrupt_seqlen = corrupt_tokens.shape[-1]

    clean_role_range = clean_ranges[0]
    corrupt_role_range = corrupt_ranges[0]

    clean_inst_range = clean_ranges[3]
    corrupt_inst_range = corrupt_ranges[3]

    clean_source_pos = base.ensure_list_pos(
        base.get_pos_from_ranges(
            clean_seqlen,
            "role_adj_adv",
            clean_role_range,
        )
    )

    corrupt_source_pos = base.ensure_list_pos(
        base.get_pos_from_ranges(
            corrupt_seqlen,
            "role_adj_adv",
            corrupt_role_range,
        )
    )

    clean_inst_pos = span_positions(clean_inst_range)
    corrupt_inst_pos = span_positions(corrupt_inst_range)

    clean_last_pos = clean_seqlen - 1
    corrupt_last_pos = corrupt_seqlen - 1

    if len(clean_source_pos) != len(corrupt_source_pos):
        raise RuntimeError(
            f"source position mismatch: "
            f"clean={clean_source_pos} corrupt={corrupt_source_pos}"
        )

    if len(clean_inst_pos) != len(corrupt_inst_pos):
        raise RuntimeError(
            f"instruction length mismatch: "
            f"clean={len(clean_inst_pos)} corrupt={len(corrupt_inst_pos)}"
        )

    # Strict feed-forward chain.
    if not (source_layer < mediator_layer < receiver_layer):
        raise RuntimeError(
            f"Invalid causal layer order: "
            f"L{source_layer} -> L{mediator_layer} -> L{receiver_layer}"
        )

    source_hook_name = base.utils.get_act_name("z", source_layer)
    mediator_hook_name = base.utils.get_act_name("z", mediator_layer)
    receiver_hook_name = base.utils.get_act_name("z", receiver_layer)

    cache_names = [
        source_hook_name,
        mediator_hook_name,
        receiver_hook_name,
    ]

    # ---------------------------------------------------------
    # Baseline clean / corrupted runs + caches
    # ---------------------------------------------------------
    clean_logits, clean_cache = model.run_with_cache(
        clean_tokens,
        names_filter=cache_names,
    )

    corrupt_logits, corrupt_cache = model.run_with_cache(
        corrupt_tokens,
        names_filter=cache_names,
    )

    clean_ld = float(
        base.logit_diff(
            clean_logits,
            correct_token_id,
            wrong_token_id,
        )
    )

    corrupted_ld = float(
        base.logit_diff(
            corrupt_logits,
            correct_token_id,
            wrong_token_id,
        )
    )

    clean_prob_diff = float(
        base.prob_diff(
            clean_logits,
            correct_token_id,
            wrong_token_id,
        )
    )

    corrupted_prob_diff = float(
        base.prob_diff(
            corrupt_logits,
            correct_token_id,
            wrong_token_id,
        )
    )

    # ---------------------------------------------------------
    # Hooks
    # ---------------------------------------------------------
    def source_patch_hook(z, hook):
        for cp, bp in zip(clean_source_pos, corrupt_source_pos):
            z[:, bp, source_head, :] = (
                clean_cache[source_hook_name][:, cp, source_head, :]
            )
        return z

    def mediator_block_hook(z, hook):
        # Reset mediator head at ALL instruction tokens
        # back to original corrupted activation.
        z[:, corrupt_inst_pos, mediator_head, :] = (
            corrupt_cache[mediator_hook_name][
                :, corrupt_inst_pos, mediator_head, :
            ]
        )
        return z

    def clean_mediator_patch_hook(z, hook):
        # Patch clean instruction-head activations into corrupted run,
        # position-by-position.
        z[:, corrupt_inst_pos, mediator_head, :] = (
            clean_cache[mediator_hook_name][
                :, clean_inst_pos, mediator_head, :
            ]
        )
        return z

    def receiver_block_hook(z, hook):
        # Last = final assistant-generation prompt position.
        z[:, corrupt_last_pos, receiver_head, :] = (
            corrupt_cache[receiver_hook_name][
                :, corrupt_last_pos, receiver_head, :
            ]
        )
        return z

    # ---------------------------------------------------------
    # C1:
    # Source patched.
    #
    # IMPORTANT:
    # capture the Instruction mediator activation ACTUALLY
    # produced downstream of the Role source patch.
    # ---------------------------------------------------------
    captured = {}

    def capture_source_induced_mediator_hook(z, hook):
        captured["mediator"] = (
            z[:, corrupt_inst_pos, mediator_head, :]
            .detach()
            .clone()
        )
        return z

    source_patched_logits = model.run_with_hooks(
        corrupt_tokens,
        fwd_hooks=[
            (source_hook_name, source_patch_hook),
            (
                mediator_hook_name,
                capture_source_induced_mediator_hook,
            ),
        ],
    )

    if "mediator" not in captured:
        raise RuntimeError(
            "Failed to capture source-induced mediator activation"
        )

    source_induced_mediator = captured["mediator"]

    # ---------------------------------------------------------
    # C2:
    # Source patched + Instruction mediator blocked.
    # Tests Role -> Instruction mediation.
    # ---------------------------------------------------------
    source_mediator_blocked_logits = model.run_with_hooks(
        corrupt_tokens,
        fwd_hooks=[
            (source_hook_name, source_patch_hook),
            (mediator_hook_name, mediator_block_hook),
        ],
    )

    # ---------------------------------------------------------
    # C3:
    # Clean Instruction mediator patched into corrupted run.
    # ---------------------------------------------------------
    mediator_patched_logits = model.run_with_hooks(
        corrupt_tokens,
        fwd_hooks=[
            (mediator_hook_name, clean_mediator_patch_hook),
        ],
    )

    # ---------------------------------------------------------
    # C4:
    # Clean mediator patched + Last receiver blocked.
    # Tests Instruction -> Last mediation.
    # ---------------------------------------------------------
    mediator_receiver_blocked_logits = model.run_with_hooks(
        corrupt_tokens,
        fwd_hooks=[
            (mediator_hook_name, clean_mediator_patch_hook),
            (receiver_hook_name, receiver_block_hook),
        ],
    )

    # ---------------------------------------------------------
    # C5/C6:
    # FULL CHAIN TEST.
    #
    # No source patch is applied in these fresh runs.
    # Instead, transplant ONLY the Instruction-head state that
    # was produced by C1 after Role source patching.
    # ---------------------------------------------------------
    def source_induced_mediator_patch_hook(z, hook):
        z[:, corrupt_inst_pos, mediator_head, :] = (
            source_induced_mediator
        )
        return z

    source_induced_mediator_logits = model.run_with_hooks(
        corrupt_tokens,
        fwd_hooks=[
            (
                mediator_hook_name,
                source_induced_mediator_patch_hook,
            ),
        ],
    )

    source_induced_mediator_receiver_blocked_logits = (
        model.run_with_hooks(
            corrupt_tokens,
            fwd_hooks=[
                (
                    mediator_hook_name,
                    source_induced_mediator_patch_hook,
                ),
                (receiver_hook_name, receiver_block_hook),
            ],
        )
    )

    # ---------------------------------------------------------
    # C7:
    # Source patch + Last receiver blocked.
    # This reproduces the old two-node Role -> Last test
    # for direct comparison across path-patching conditions.
    # ---------------------------------------------------------
    source_receiver_blocked_logits = model.run_with_hooks(
        corrupt_tokens,
        fwd_hooks=[
            (source_hook_name, source_patch_hook),
            (receiver_hook_name, receiver_block_hook),
        ],
    )

    # ---------------------------------------------------------
    # Convert all runs to label-aware LD / probability difference
    # ---------------------------------------------------------
    def get_ld(logits):
        return float(
            base.logit_diff(
                logits,
                correct_token_id,
                wrong_token_id,
            )
        )

    def get_pd(logits):
        return float(
            base.prob_diff(
                logits,
                correct_token_id,
                wrong_token_id,
            )
        )

    source_patched_ld = get_ld(source_patched_logits)
    source_mediator_blocked_ld = get_ld(
        source_mediator_blocked_logits
    )

    mediator_patched_ld = get_ld(mediator_patched_logits)
    mediator_receiver_blocked_ld = get_ld(
        mediator_receiver_blocked_logits
    )

    source_induced_mediator_ld = get_ld(
        source_induced_mediator_logits
    )

    source_induced_mediator_receiver_blocked_ld = get_ld(
        source_induced_mediator_receiver_blocked_logits
    )

    source_receiver_blocked_ld = get_ld(
        source_receiver_blocked_logits
    )

    # ---------------------------------------------------------
    # Core effects
    # ---------------------------------------------------------
    clean_corrupt_gap = clean_ld - corrupted_ld

    # Overall recovery caused by Role source patch
    source_recovery = source_patched_ld - corrupted_ld

    # Stage A: Role -> Instruction
    role_to_inst_drop = (
        source_patched_ld
        - source_mediator_blocked_ld
    )

    # Independent Instruction clean-patch recovery
    mediator_clean_recovery = (
        mediator_patched_ld
        - corrupted_ld
    )

    # Stage B: Instruction -> Last
    inst_to_last_drop = (
        mediator_patched_ld
        - mediator_receiver_blocked_ld
    )

    # Effect carried by the Instruction state specifically induced
    # by the Role source patch.
    source_induced_mediator_recovery = (
        source_induced_mediator_ld
        - corrupted_ld
    )

    # Stage C: full Role -> Instruction -> Last chain.
    chain_to_last_drop = (
        source_induced_mediator_ld
        - source_induced_mediator_receiver_blocked_ld
    )

    # Old two-node comparison:
    # Role source -> Last receiver
    source_to_last_drop = (
        source_patched_ld
        - source_receiver_blocked_ld
    )

    # ---------------------------------------------------------
    # Return detailed sample-level record
    # ---------------------------------------------------------
    return {
        "clean_ld": clean_ld,
        "corrupted_ld": corrupted_ld,
        "clean_corrupt_gap": clean_corrupt_gap,

        "source_patched_ld": source_patched_ld,
        "source_mediator_blocked_ld":
            source_mediator_blocked_ld,

        "mediator_patched_ld": mediator_patched_ld,
        "mediator_receiver_blocked_ld":
            mediator_receiver_blocked_ld,

        "source_induced_mediator_ld":
            source_induced_mediator_ld,
        "source_induced_mediator_receiver_blocked_ld":
            source_induced_mediator_receiver_blocked_ld,

        "source_receiver_blocked_ld":
            source_receiver_blocked_ld,

        "source_recovery": source_recovery,

        "role_to_inst_drop": role_to_inst_drop,
        "role_to_inst_fraction":
            safe_div(role_to_inst_drop, source_recovery),

        "mediator_clean_recovery":
            mediator_clean_recovery,

        "inst_to_last_drop": inst_to_last_drop,
        "inst_to_last_fraction":
            safe_div(
                inst_to_last_drop,
                mediator_clean_recovery,
            ),

        "source_induced_mediator_recovery":
            source_induced_mediator_recovery,

        "chain_to_last_drop": chain_to_last_drop,
        "chain_to_last_fraction":
            safe_div(
                chain_to_last_drop,
                source_induced_mediator_recovery,
            ),

        "source_to_last_drop":
            source_to_last_drop,
        "source_to_last_fraction":
            safe_div(
                source_to_last_drop,
                source_recovery,
            ),

        "normalized_source_recovery":
            safe_div(source_recovery, clean_corrupt_gap),

        "normalized_role_to_inst_drop":
            safe_div(role_to_inst_drop, clean_corrupt_gap),

        "normalized_mediator_clean_recovery":
            safe_div(
                mediator_clean_recovery,
                clean_corrupt_gap,
            ),

        "normalized_inst_to_last_drop":
            safe_div(inst_to_last_drop, clean_corrupt_gap),

        "normalized_source_induced_mediator_recovery":
            safe_div(
                source_induced_mediator_recovery,
                clean_corrupt_gap,
            ),

        "normalized_chain_to_last_drop":
            safe_div(chain_to_last_drop, clean_corrupt_gap),

        "normalized_source_to_last_drop":
            safe_div(source_to_last_drop, clean_corrupt_gap),

        "clean_prob_diff": clean_prob_diff,
        "corrupted_prob_diff": corrupted_prob_diff,

        "source_patched_prob_diff":
            get_pd(source_patched_logits),

        "source_mediator_blocked_prob_diff":
            get_pd(source_mediator_blocked_logits),

        "mediator_patched_prob_diff":
            get_pd(mediator_patched_logits),

        "mediator_receiver_blocked_prob_diff":
            get_pd(mediator_receiver_blocked_logits),

        "source_induced_mediator_prob_diff":
            get_pd(source_induced_mediator_logits),

        "source_induced_mediator_receiver_blocked_prob_diff":
            get_pd(
                source_induced_mediator_receiver_blocked_logits
            ),

        "source_receiver_blocked_prob_diff":
            get_pd(source_receiver_blocked_logits),

        "clean_source_pos":
            json.dumps(clean_source_pos),

        "corrupt_source_pos":
            json.dumps(corrupt_source_pos),

        "clean_inst_pos":
            json.dumps(clean_inst_pos),

        "corrupt_inst_pos":
            json.dumps(corrupt_inst_pos),

        "clean_last_pos":
            clean_last_pos,

        "corrupt_last_pos":
            corrupt_last_pos,
    }

MODEL_CONFIGS = {
    "llama": {
        "transformerlens_name": "meta-llama/Llama-3.1-8B-Instruct",
        "loader": "direct",
        "use_fast": None,
        "yes_form": " Yes",
        "no_form": " No",
        "expected_yes": None,
        "expected_no": None,
        "role_file": (
            "llama_best_token_combo_selected20_nested_for_patching.json"
        ),
    },
    "qwen": {
        "transformerlens_name": "Qwen/Qwen2.5-7B-Instruct",
        "loader": "hf",
        "use_fast": False,
        "yes_form": "Yes",
        "no_form": "No",
        "expected_yes": 9454,
        "expected_no": 2753,
        "role_file": (
            "qwen_best_token_combo_selected20_nested_for_patching.json"
        ),
    },
    "mistral": {
        "transformerlens_name": "mistralai/Mistral-7B-Instruct-v0.3",
        "loader": "hf",
        "use_fast": False,
        "yes_form": "Yes",
        "no_form": "No",
        "expected_yes": 6360,
        "expected_no": 2538,
        "role_file": (
            "mistral_best_token_combo_selected20_nested_for_patching.json"
        ),
    },
}


DATASET_CONFIGS = {
    "dl19": {
        "ir_dataset": "msmarco-passage/trec-dl-2019",
        "max_qids": 43,
    },
    "dl20": {
        "ir_dataset": "msmarco-passage/trec-dl-2020",
        "max_qids": 54,
    },
}


def _resolve_path(value, default):
    """Resolve an optional CLI path relative to the repository root."""
    p = Path(value).expanduser() if value is not None else default

    if not p.is_absolute():
        p = REPO_ROOT / p

    return p.resolve()


def _answer_token_ids(tokenizer, model_key):
    """Return the single-token Yes/No ids used by the original runs."""
    cfg = MODEL_CONFIGS[model_key]

    yes_tokens = tokenizer.encode(
        cfg["yes_form"],
        add_special_tokens=False,
    )
    no_tokens = tokenizer.encode(
        cfg["no_form"],
        add_special_tokens=False,
    )

    if len(yes_tokens) != 1 or len(no_tokens) != 1:
        raise RuntimeError(
            "Expected single-token Yes/No answers, but got "
            f"Yes={yes_tokens}, No={no_tokens}"
        )

    expected_yes = cfg["expected_yes"]
    expected_no = cfg["expected_no"]

    if expected_yes is not None and yes_tokens != [expected_yes]:
        raise RuntimeError(
            f"{model_key}: Yes token mismatch: "
            f"got {yes_tokens}, expected {[expected_yes]}"
        )

    if expected_no is not None and no_tokens != [expected_no]:
        raise RuntimeError(
            f"{model_key}: No token mismatch: "
            f"got {no_tokens}, expected {[expected_no]}"
        )

    return yes_tokens[0], no_tokens[0]


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Three-stage pointwise path patching: "
            "Role Adj+Adv -> Instruction -> Last"
        )
    )

    parser.add_argument(
        "--model",
        required=True,
        choices=sorted(MODEL_CONFIGS),
    )

    parser.add_argument(
        "--dataset",
        required=True,
        choices=sorted(DATASET_CONFIGS),
    )

    parser.add_argument(
        "--model-path",
        required=True,
        help=(
            "Local checkpoint path or Hugging Face model identifier."
        ),
    )

    parser.add_argument(
        "--model-name",
        default=None,
        help=(
            "Optional TransformerLens architecture-name override."
        ),
    )

    parser.add_argument(
        "--pairs-path",
        default=None,
        help="Optional override for the controlled-pair TSV.",
    )

    parser.add_argument(
        "--role-json-path",
        default=None,
        help="Optional override for the selected20 role JSON.",
    )

    parser.add_argument(
        "--candidates-path",
        default=None,
        help="Optional override for the candidate-path CSV.",
    )

    parser.add_argument(
        "--output-dir",
        default=None,
        help="Optional output directory.",
    )

    parser.add_argument(
        "--max-qids",
        type=int,
        default=None,
    )

    parser.add_argument(
        "--max-paths",
        type=int,
        default=None,
    )

    parser.add_argument(
        "--max-role-pairs",
        type=int,
        default=10,
    )

    parser.add_argument(
        "--device",
        default="cuda",
    )

    parser.add_argument(
        "--dtype",
        choices=["bfloat16", "float16"],
        default="bfloat16",
    )

    parser.add_argument(
        "--local-files-only",
        action="store_true",
        help=(
            "Require model/tokenizer files to already exist locally."
        ),
    )

    args = parser.parse_args()

    model_cfg = MODEL_CONFIGS[args.model]
    dataset_cfg = DATASET_CONFIGS[args.dataset]

    # Preserve the variable name used by the validated experiment loop.
    args.dataset_name = dataset_cfg["ir_dataset"]

    if args.max_qids is None:
        args.max_qids = dataset_cfg["max_qids"]

    default_pairs = (
        REPO_ROOT
        / "data"
        / "pairs"
        / "pointwise"
        / f"{args.dataset}.tsv"
    )

    default_roles = (
        REPO_ROOT
        / "roles"
        / args.model
        / "selected20"
        / model_cfg["role_file"]
    )

    default_candidates = (
        REPO_ROOT
        / "patching"
        / "pointwise"
        / "path_patching"
        / "candidates"
        / args.model
        / f"{args.dataset}.csv"
    )

    default_output = (
        REPO_ROOT
        / "results"
        / "pointwise_path_patching"
        / args.model
        / args.dataset
    )

    pairs_path = _resolve_path(
        args.pairs_path,
        default_pairs,
    )
    role_json_path = _resolve_path(
        args.role_json_path,
        default_roles,
    )
    candidates_path = _resolve_path(
        args.candidates_path,
        default_candidates,
    )
    output_dir = _resolve_path(
        args.output_dir,
        default_output,
    )

    output_dir.mkdir(parents=True, exist_ok=True)

    # prompt_generator reads ROLE_JSON_PATH internally.
    os.environ["ROLE_JSON_PATH"] = str(role_json_path)

    print("=" * 80)
    print("POINTWISE THREE-STAGE PATH PATCHING")
    print("Role Adj+Adv -> Instruction -> Last")
    print("=" * 80)
    print("model             =", args.model)
    print("dataset           =", args.dataset)
    print("dataset_name      =", args.dataset_name)
    print("model_path        =", args.model_path)
    print("pairs_path        =", pairs_path)
    print("role_json_path    =", role_json_path)
    print("candidates_path   =", candidates_path)
    print("output_dir        =", output_dir)
    print("max_qids          =", args.max_qids)
    print("max_paths         =", args.max_paths)
    print("max_role_pairs    =", args.max_role_pairs)

    for path in [
        pairs_path,
        role_json_path,
        candidates_path,
    ]:
        if not path.is_file():
            raise FileNotFoundError(path)

    candidates = pd.read_csv(candidates_path)

    required_cols = {
        "candidate_group",
        "test_doc_source",
        "source_pos_type",
        "source_layer",
        "source_head",
        "mediator_pos_type",
        "mediator_layer",
        "mediator_head",
        "receiver_pos_type",
        "receiver_layer",
        "receiver_head",
    }

    missing = required_cols - set(candidates.columns)

    if missing:
        raise ValueError(
            f"Candidate CSV missing columns: {sorted(missing)}"
        )

    if not (
        candidates["source_pos_type"] == "role_adj_adv"
    ).all():
        raise ValueError(
            "All candidates must use "
            "source_pos_type=role_adj_adv"
        )

    if not (
        candidates["mediator_pos_type"] == "inst_all"
    ).all():
        raise ValueError(
            "All candidates must use "
            "mediator_pos_type=inst_all"
        )

    if not (
        candidates["receiver_pos_type"] == "last"
    ).all():
        raise ValueError(
            "All candidates must use "
            "receiver_pos_type=last"
        )

    good_order = (
        candidates["source_layer"]
        < candidates["mediator_layer"]
    ) & (
        candidates["mediator_layer"]
        < candidates["receiver_layer"]
    )

    if not good_order.all():
        bad = candidates.loc[~good_order]
        raise ValueError(
            "Invalid non-feed-forward candidates:\n"
            + bad.to_string(index=False)
        )

    if args.max_paths is not None:
        candidates = candidates.head(
            args.max_paths
        ).copy()

    role_pairs = base.ROLE_PAIRS[
        : args.max_role_pairs
    ]

    print("candidate paths   =", len(candidates))
    print("role pairs        =", len(role_pairs))
    print("CANDIDATE AUDIT: PASS")

    roles = base.load_role_json(role_json_path)

    tokenizer_kwargs = {
        "trust_remote_code": True,
        "local_files_only": args.local_files_only,
    }

    if model_cfg["use_fast"] is not None:
        tokenizer_kwargs["use_fast"] = (
            model_cfg["use_fast"]
        )

    tokenizer = base.AutoTokenizer.from_pretrained(
        args.model_path,
        **tokenizer_kwargs,
    )

    tokenizer.use_default_system_prompt = False
    tokenizer.pad_token = tokenizer.eos_token

    yes_id, no_id = _answer_token_ids(
        tokenizer,
        args.model,
    )

    print("yes_id =", yes_id, "no_id =", no_id)

    torch_dtype = (
        torch.bfloat16
        if args.dtype == "bfloat16"
        else torch.float16
    )

    transformer_lens_name = (
        args.model_name
        or model_cfg["transformerlens_name"]
    )

    if model_cfg["loader"] == "direct":
        print(
            "[INFO] Loading HookedTransformer directly..."
        )

        model = (
            base.HookedTransformer
            .from_pretrained_no_processing(
                args.model_path,
                hf_model=None,
                tokenizer=tokenizer,
                device=args.device,
                dtype=torch_dtype,
            )
        )

    else:
        print("[INFO] Loading native HF model...")

        hf_model = (
            base.AutoModelForCausalLM
            .from_pretrained(
                args.model_path,
                local_files_only=(
                    args.local_files_only
                ),
                trust_remote_code=True,
                torch_dtype=torch_dtype,
                low_cpu_mem_usage=True,
            )
        )

        print(
            "[INFO] Loading HookedTransformer "
            f"as {transformer_lens_name}..."
        )

        model = (
            base.HookedTransformer
            .from_pretrained_no_processing(
                transformer_lens_name,
                hf_model=hf_model,
                tokenizer=tokenizer,
                device=args.device,
                dtype=torch_dtype,
            )
        )

    model.eval()

    all_rows = []

    for candidate_index, cand in candidates.reset_index(drop=True).iterrows():
        chain_id = f"chain_{candidate_index + 1:03d}"

        candidate_group = str(cand["candidate_group"])
        doc_source = str(cand["test_doc_source"])

        source_layer = int(cand["source_layer"])
        source_head = int(cand["source_head"])

        mediator_layer = int(cand["mediator_layer"])
        mediator_head = int(cand["mediator_head"])

        receiver_layer = int(cand["receiver_layer"])
        receiver_head = int(cand["receiver_head"])

        chain_name = (
            f"L{source_layer}H{source_head}_role"
            f"_to_L{mediator_layer}H{mediator_head}_inst"
            f"_to_L{receiver_layer}H{receiver_head}_last"
        )

        print()
        print("=" * 100)
        print(
            f"{chain_id} | {candidate_group} | {doc_source} | "
            f"{chain_name}"
        )
        print("=" * 100)

        pairs = base.load_pairs_tsv(
            pairs_path,
            doc_source=doc_source,
        )

        if args.max_qids is not None:
            pairs = pairs.head(args.max_qids).copy()

        queries, docs = (
            base.load_queries_docs_from_ir_datasets(
                args.dataset_name,
                pairs,
            )
        )

        # Label-aware direction identical to previous patching.
        if doc_source == "irrelevance":
            correct_token_id = no_id
            wrong_token_id = yes_id
        elif doc_source == "relevance":
            correct_token_id = yes_id
            wrong_token_id = no_id
        else:
            raise ValueError(
                f"Unsupported doc_source={doc_source}"
            )

        for clean_role, corrupt_role in role_pairs:
            clean_pkg = base.role_to_prompt_pkg(
                roles,
                clean_role,
            )

            corrupt_pkg = base.role_to_prompt_pkg(
                roles,
                corrupt_role,
            )

            clean_prompt_tem = clean_pkg[1]
            clean_role_text = clean_pkg[2]
            instruction = clean_pkg[3]

            corrupt_prompt_tem = corrupt_pkg[1]
            corrupt_role_text = corrupt_pkg[2]

            if corrupt_pkg[3] != instruction:
                raise RuntimeError(
                    "Clean/corrupt instruction strings differ"
                )

            sample_rows = []

            iterator = tqdm(
                pairs.iterrows(),
                total=len(pairs),
                desc=(
                    f"{chain_id} "
                    f"{clean_role}->{corrupt_role}"
                ),
            )

            for _, ex in iterator:
                qid = str(ex["qid"])
                docid = str(ex["docid"])
                label = int(ex["label"])

                query = queries[qid]
                doc_text = docs[docid]

                clean_prompt = clean_prompt_tem.format(
                    text=doc_text,
                    query=query,
                )

                corrupt_prompt = corrupt_prompt_tem.format(
                    text=doc_text,
                    query=query,
                )

                clean_ranges = base.get_pointwise_ranges(
                    tokenizer,
                    clean_prompt,
                    clean_role_text,
                    query,
                    doc_text,
                    instruction,
                    use_chat=True,
                )

                corrupt_ranges = base.get_pointwise_ranges(
                    tokenizer,
                    corrupt_prompt,
                    corrupt_role_text,
                    query,
                    doc_text,
                    instruction,
                    use_chat=True,
                )

                clean_tokens = tokenizer.apply_chat_template(
                    [
                        {
                            "role": "user",
                            "content": clean_prompt,
                        }
                    ],
                    return_tensors="pt",
                    padding="longest",
                    max_length=2048,
                    truncation=True,
                    add_generation_prompt=True,
                ).to(args.device)

                corrupt_tokens = tokenizer.apply_chat_template(
                    [
                        {
                            "role": "user",
                            "content": corrupt_prompt,
                        }
                    ],
                    return_tensors="pt",
                    padding="longest",
                    max_length=2048,
                    truncation=True,
                    add_generation_prompt=True,
                ).to(args.device)

                metrics = run_one_example(
                    model=model,
                    clean_tokens=clean_tokens,
                    corrupt_tokens=corrupt_tokens,
                    clean_ranges=clean_ranges,
                    corrupt_ranges=corrupt_ranges,

                    source_layer=source_layer,
                    source_head=source_head,

                    mediator_layer=mediator_layer,
                    mediator_head=mediator_head,

                    receiver_layer=receiver_layer,
                    receiver_head=receiver_head,

                    correct_token_id=correct_token_id,
                    wrong_token_id=wrong_token_id,
                )

                row = {
                    "chain_id": chain_id,
                    "chain_name": chain_name,

                    "candidate_group":
                        candidate_group,

                    "doc_source":
                        doc_source,

                    "source_pos_type":
                        "role_adj_adv",

                    "source_layer":
                        source_layer,

                    "source_head":
                        source_head,

                    "mediator_pos_type":
                        "inst_all",

                    "mediator_layer":
                        mediator_layer,

                    "mediator_head":
                        mediator_head,

                    "receiver_pos_type":
                        "last",

                    "receiver_layer":
                        receiver_layer,

                    "receiver_head":
                        receiver_head,

                    "clean_role":
                        clean_role,

                    "corrupt_role":
                        corrupt_role,

                    "qid":
                        qid,

                    "docid":
                        docid,

                    "label":
                        label,

                    **metrics,
                }

                sample_rows.append(row)

            role_df = pd.DataFrame(sample_rows)

            role_out = output_dir / (
                f"{chain_id}__{doc_source}"
                f"__{chain_name}"
                f"__{clean_role}_to_{corrupt_role}.csv"
            )

            role_df.to_csv(
                role_out,
                index=False,
            )

            print(
                "saved role samples:",
                role_out,
            )

            all_rows.extend(sample_rows)

            # -------------------------------------------------
            # Refresh aggregate samples and chain summary.
            # -------------------------------------------------
            all_df = pd.DataFrame(all_rows)

            all_save = (
                output_dir
                / "ALL_samples__three_stage_role_inst_last.csv"
            )

            all_df.to_csv(
                all_save,
                index=False,
            )

            group_cols = [
                "chain_id",
                "chain_name",
                "candidate_group",
                "doc_source",

                "source_pos_type",
                "source_layer",
                "source_head",

                "mediator_pos_type",
                "mediator_layer",
                "mediator_head",

                "receiver_pos_type",
                "receiver_layer",
                "receiver_head",
            ]

            metric_cols = [
                "clean_ld",
                "corrupted_ld",
                "clean_corrupt_gap",

                "source_patched_ld",
                "source_mediator_blocked_ld",

                "mediator_patched_ld",
                "mediator_receiver_blocked_ld",

                "source_induced_mediator_ld",
                "source_induced_mediator_receiver_blocked_ld",

                "source_receiver_blocked_ld",

                "source_recovery",

                "role_to_inst_drop",
                "role_to_inst_fraction",

                "mediator_clean_recovery",

                "inst_to_last_drop",
                "inst_to_last_fraction",

                "source_induced_mediator_recovery",

                "chain_to_last_drop",
                "chain_to_last_fraction",

                "source_to_last_drop",
                "source_to_last_fraction",

                "normalized_source_recovery",
                "normalized_role_to_inst_drop",
                "normalized_mediator_clean_recovery",
                "normalized_inst_to_last_drop",
                "normalized_source_induced_mediator_recovery",
                "normalized_chain_to_last_drop",
                "normalized_source_to_last_drop",
            ]

            summary = (
                all_df
                .groupby(group_cols, as_index=False)
                .agg(
                    n=("qid", "count"),
                    **{
                        col: (col, "mean")
                        for col in metric_cols
                    },
                )
            )

            # -------------------------------------------------
            # IMPORTANT:
            # Ratio-like summary metrics must be computed as
            #
            #     mean(numerator) / mean(denominator)
            #
            # NOT as mean(per-sample numerator/denominator).
            #
            # The latter is unstable when denominators are small
            # or change sign across qids.
            #
            # Sample-level ratio columns in ALL_samples are kept
            # unchanged; only aggregate SUMMARY values are
            # overwritten here.
            # -------------------------------------------------
            def set_aggregate_ratio(name, numerator, denominator):
                summary[name] = [
                    safe_div(float(n), float(d))
                    for n, d in zip(
                        summary[numerator],
                        summary[denominator],
                    )
                ]

            # Mediation fractions
            set_aggregate_ratio(
                "role_to_inst_fraction",
                "role_to_inst_drop",
                "source_recovery",
            )

            set_aggregate_ratio(
                "inst_to_last_fraction",
                "inst_to_last_drop",
                "mediator_clean_recovery",
            )

            set_aggregate_ratio(
                "chain_to_last_fraction",
                "chain_to_last_drop",
                "source_induced_mediator_recovery",
            )

            set_aggregate_ratio(
                "source_to_last_fraction",
                "source_to_last_drop",
                "source_recovery",
            )

            # Normalized effects relative to the clean-corrupt gap
            set_aggregate_ratio(
                "normalized_source_recovery",
                "source_recovery",
                "clean_corrupt_gap",
            )

            set_aggregate_ratio(
                "normalized_role_to_inst_drop",
                "role_to_inst_drop",
                "clean_corrupt_gap",
            )

            set_aggregate_ratio(
                "normalized_mediator_clean_recovery",
                "mediator_clean_recovery",
                "clean_corrupt_gap",
            )

            set_aggregate_ratio(
                "normalized_inst_to_last_drop",
                "inst_to_last_drop",
                "clean_corrupt_gap",
            )

            set_aggregate_ratio(
                "normalized_source_induced_mediator_recovery",
                "source_induced_mediator_recovery",
                "clean_corrupt_gap",
            )

            set_aggregate_ratio(
                "normalized_chain_to_last_drop",
                "chain_to_last_drop",
                "clean_corrupt_gap",
            )

            set_aggregate_ratio(
                "normalized_source_to_last_drop",
                "source_to_last_drop",
                "clean_corrupt_gap",
            )

            summary_save = (
                output_dir
                / "SUMMARY_chains__three_stage_role_inst_last.csv"
            )

            summary.to_csv(
                summary_save,
                index=False,
            )

            print(
                "updated summary:",
                summary_save,
            )

    print()
    print("=" * 80)
    print("THREE-STAGE PATH PATCHING DONE")
    print("=" * 80)

    print("output_dir =", output_dir)
    print("samples    =", len(all_rows))


if __name__ == "__main__":
    main()
